### ISSUE TITLE
No longer available to install using pip/pip3

### ISSUE THREAD

**Issue by LapplandsCohan** [u9n/enron-modbus#4]
Trying to install using `pip` gives `ERROR: No matching distribution found for enron-modbus`, and I can't find it on [PyPI](https://pypi.org) either.

**Comment by Krolken** [comment]
Hmm. Did we never publish it?...

We stopped this implementation as the devices we were working on was not in fact pure Enron Modbus but a sub protocol with a completely different implementation in historical readout. So we put that obscure implementation in our closed source code instead.

I will remove the text about installation.
